spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth
          uri: lb://accounts-service
          predicates:
            - Path=/auth/**
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:1301/eureka