spring:
  application:
    name: eureka-server

server:
  port: 1301

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:1301/eureka

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF